VAR_SCALE = 'scale'
VAR_SCALE_DEFAULT = 0.5
VAR_MONITOR = 'monitor'
VAR_MONITOR_DEFAULT = 0
VAR_SHOULD_UPDATE_COMMANDS = 'update_commands'
VAR_SHOULD_UPDATE_COMMANDS_DEFAULT = True

COMMAND_SET_VAR = 'set_var'
COMMAND_SEND_SCREENSHOT = 'send_screenshot'
COMMAND_NEW_COMMAND = 'command'